from __future__ import annotations

from datetime import datetime, timedelta

from nexus.database import Contract, Supplier, Negotiation, get_db_session


def generate_contract(negotiation_id: str) -> str:
    with get_db_session() as db:
        neg: Negotiation = db.query(Negotiation).filter(Negotiation.id == negotiation_id).first()
        if not neg:
            raise ValueError("Negotiation not found")
        supplier: Supplier = db.query(Supplier).filter(Supplier.id == neg.supplier_id).first()
        if not supplier:
            raise ValueError("Supplier not found")

        contract_id = f"CONTRACT-{negotiation_id[:8].upper()}"
        discount_pct = 0.0
        if neg.initial_supplier_ask and neg.final_price and neg.initial_supplier_ask > 0:
            discount_pct = ((neg.initial_supplier_ask - neg.final_price) / neg.initial_supplier_ask) * 100

        delivery_date = (datetime.utcnow() + timedelta(days=supplier.lead_time_days or 0)).strftime("%Y-%m-%d")
        content = f"""
PROCUREMENT CONTRACT
====================
Contract ID         : {contract_id}
Generated At        : {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
Status              : BINDING UPON COUNTERSIGNATURE

PARTIES
-------
Buyer               : Nexus Procurement System (buyer-nexus)
Supplier            : {supplier.name} ({supplier.id})
Supplier Region     : {supplier.region}

ORDER DETAILS
-------------
Product             : {neg.product}
Quantity            : {neg.quantity} units
Unit Price          : €{neg.final_price:.2f}
Total Value         : €{neg.final_price * neg.quantity:.2f}
Currency            : EUR
Payment Terms       : Net-30

DELIVERY
--------
Destination         : {neg.destination_region}
Lead Time           : {supplier.lead_time_days} days from PO confirmation
Latest Delivery By  : {delivery_date}

QUALITY & COMPLIANCE
--------------------
Certifications      : {supplier.certifications}
Inspection Right    : Buyer reserves right to inspect goods on delivery

NEGOTIATION SUMMARY
-------------------
Rounds Taken        : {neg.current_round}
Initial Supplier Ask: €{neg.initial_supplier_ask:.2f}/unit
Final Agreed Price  : €{neg.final_price:.2f}/unit
Discount Achieved   : {discount_pct:.1f}%

TERMS
-----
1. Supplier guarantees delivery within the lead time stated above.
2. Payment issued within 30 days of delivery confirmation.
3. Defective units replaced at no cost within 14 days of delivery.
4. This contract covers this order only and implies no future commitment.
5. Governing law: EU Commercial Code.

SIGNATURES
----------
Buyer Authorized By    : ______________________    Date : __________
Supplier Authorized By : ______________________    Date : __________

[ Generated by Nexus Procurement System ]
[ Negotiation ID : {negotiation_id} ]
""".strip()

        existing = db.query(Contract).filter(Contract.id == contract_id).first()
        if not existing:
            db.add(
                Contract(
                    id=contract_id,
                    negotiation_id=negotiation_id,
                    supplier_id=supplier.id,
                    total_value=neg.final_price * neg.quantity,
                    content=content,
                )
            )
            db.commit()
        return content
