from __future__ import annotations

import json
from datetime import datetime

from nexus.database import Supplier, get_db_session


SEED_SUPPLIERS = [
    {
        "id": "techparts-eu",
        "name": "TechParts EU",
        "country": "EU",
        "region": "EU",
        "capabilities": ["sensors", "motors"],
        "base_price_map": {"sensors": 4.20, "motors": 12.50, "default": 5.00},
        "price_floor_map": {"sensors": 3.80, "motors": 11.30, "default": 4.50},
        "lead_time_days": 10,
        "certifications": ["ISO-9001", "CE"],
        "trust_score": 0.85,
        "fit_score": 0.50,
    },
    {
        "id": "sensortech-de",
        "name": "SensorTech DE",
        "country": "EU",
        "region": "EU",
        "capabilities": ["sensors"],
        "base_price_map": {"sensors": 4.67, "default": 4.67},
        "price_floor_map": {"sensors": 3.92, "default": 3.92},
        "lead_time_days": 8,
        "certifications": ["ISO-9001", "ISO-14001"],
        "trust_score": 0.90,
        "fit_score": 0.55,
    },
    {
        "id": "shenzhen-supply",
        "name": "Shenzhen Supply",
        "country": "ASIA",
        "region": "ASIA",
        "capabilities": ["sensors", "cables"],
        "base_price_map": {"sensors": 3.10, "cables": 1.20, "default": 3.10},
        "price_floor_map": {"sensors": 2.80, "cables": 1.00, "default": 2.80},
        "lead_time_days": 14,
        "certifications": ["ISO-9001"],
        "trust_score": 0.70,
        "fit_score": 0.45,
    },
    {
        "id": "electro-nl",
        "name": "Electro NL",
        "country": "EU",
        "region": "EU",
        "capabilities": ["connectors", "cables"],
        "base_price_map": {"connectors": 2.50, "cables": 1.30, "default": 2.50},
        "price_floor_map": {"connectors": 2.10, "cables": 1.05, "default": 2.10},
        "lead_time_days": 9,
        "certifications": ["CE"],
        "trust_score": 0.78,
        "fit_score": 0.50,
    },
    {
        "id": "newco-fresh",
        "name": "NewCo Fresh",
        "country": "EU",
        "region": "EU",
        "capabilities": ["sensors"],
        "base_price_map": {"sensors": 4.00, "default": 4.00},
        "price_floor_map": {"sensors": 3.60, "default": 3.60},
        "lead_time_days": 12,
        "certifications": ["ISO-9001"],
        "trust_score": 0.75,
        "fit_score": 0.48,
    },
    {
        "id": "atlantic-cables-us",
        "name": "Atlantic Cables US",
        "country": "US",
        "region": "North America",
        "capabilities": ["cables", "connectors"],
        "base_price_map": {"cables": 1.35, "connectors": 2.40, "default": 1.35},
        "price_floor_map": {"cables": 1.10, "connectors": 2.05, "default": 1.10},
        "lead_time_days": 9,
        "certifications": ["UL", "ISO-9001"],
        "trust_score": 0.80,
        "fit_score": 0.52,
    },
    {
        "id": "nordic-displays-se",
        "name": "Nordic Displays SE",
        "country": "SE",
        "region": "EU",
        "capabilities": ["displays"],
        "base_price_map": {"displays": 18.50, "default": 18.50},
        "price_floor_map": {"displays": 16.80, "default": 16.80},
        "lead_time_days": 11,
        "certifications": ["CE", "ISO-9001"],
        "trust_score": 0.83,
        "fit_score": 0.56,
    },
    {
        "id": "texon-motors-us",
        "name": "Texon Motors",
        "country": "US",
        "region": "North America",
        "capabilities": ["motors"],
        "base_price_map": {"motors": 12.90, "default": 12.90},
        "price_floor_map": {"motors": 11.70, "default": 11.70},
        "lead_time_days": 10,
        "certifications": ["UL"],
        "trust_score": 0.79,
        "fit_score": 0.50,
    },
    {
        "id": "pacific-battery-jp",
        "name": "Pacific Battery JP",
        "country": "JP",
        "region": "APAC",
        "capabilities": ["batteries"],
        "base_price_map": {"batteries": 8.40, "default": 8.40},
        "price_floor_map": {"batteries": 7.60, "default": 7.60},
        "lead_time_days": 13,
        "certifications": ["JIS", "ISO-14001"],
        "trust_score": 0.86,
        "fit_score": 0.58,
    },
    {
        "id": "gulf-connectors-ae",
        "name": "Gulf Connectors",
        "country": "AE",
        "region": "MENA",
        "capabilities": ["connectors"],
        "base_price_map": {"connectors": 2.60, "default": 2.60},
        "price_floor_map": {"connectors": 2.25, "default": 2.25},
        "lead_time_days": 12,
        "certifications": ["ISO-9001"],
        "trust_score": 0.74,
        "fit_score": 0.47,
    },
    {
        "id": "seoul-sensors-kr",
        "name": "Seoul Sensors",
        "country": "KR",
        "region": "APAC",
        "capabilities": ["sensors"],
        "base_price_map": {"sensors": 4.25, "default": 4.25},
        "price_floor_map": {"sensors": 3.75, "default": 3.75},
        "lead_time_days": 9,
        "certifications": ["KS", "ISO-9001"],
        "trust_score": 0.84,
        "fit_score": 0.55,
    },
    {
        "id": "iberia-electro-es",
        "name": "Iberia Electro",
        "country": "ES",
        "region": "EU",
        "capabilities": ["sensors", "cables", "connectors"],
        "base_price_map": {"sensors": 4.10, "cables": 1.25, "connectors": 2.35, "default": 2.90},
        "price_floor_map": {"sensors": 3.70, "cables": 1.05, "connectors": 2.00, "default": 2.50},
        "lead_time_days": 10,
        "certifications": ["CE"],
        "trust_score": 0.77,
        "fit_score": 0.50,
    },
    {
        "id": "delta-motors-in",
        "name": "Delta Motors IN",
        "country": "IN",
        "region": "APAC",
        "capabilities": ["motors", "other"],
        "base_price_map": {"motors": 11.80, "other": 6.50, "default": 6.50},
        "price_floor_map": {"motors": 10.90, "other": 5.90, "default": 5.90},
        "lead_time_days": 15,
        "certifications": ["ISO-9001"],
        "trust_score": 0.72,
        "fit_score": 0.46,
    },
    {
        "id": "alpine-battery-ch",
        "name": "Alpine Battery",
        "country": "CH",
        "region": "EU",
        "capabilities": ["batteries", "sensors"],
        "base_price_map": {"batteries": 8.10, "sensors": 4.30, "default": 5.00},
        "price_floor_map": {"batteries": 7.40, "sensors": 3.90, "default": 4.50},
        "lead_time_days": 10,
        "certifications": ["ISO-9001", "CE"],
        "trust_score": 0.82,
        "fit_score": 0.54,
    },
    {
        "id": "baltic-displays-pl",
        "name": "Baltic Displays",
        "country": "PL",
        "region": "EU",
        "capabilities": ["displays", "cables"],
        "base_price_map": {"displays": 17.20, "cables": 1.30, "default": 7.50},
        "price_floor_map": {"displays": 15.80, "cables": 1.10, "default": 6.80},
        "lead_time_days": 12,
        "certifications": ["CE"],
        "trust_score": 0.78,
        "fit_score": 0.51,
    },
    {
        "id": "canstack-components-ca",
        "name": "CanStack Components",
        "country": "CA",
        "region": "North America",
        "capabilities": ["connectors", "cables", "sensors"],
        "base_price_map": {"connectors": 2.45, "cables": 1.20, "sensors": 4.15, "default": 2.90},
        "price_floor_map": {"connectors": 2.05, "cables": 1.05, "sensors": 3.70, "default": 2.50},
        "lead_time_days": 9,
        "certifications": ["UL", "ISO-9001"],
        "trust_score": 0.81,
        "fit_score": 0.53,
    },
    {
        "id": "tierra-cables-mx",
        "name": "Tierra Cables MX",
        "country": "MX",
        "region": "LATAM",
        "capabilities": ["cables"],
        "base_price_map": {"cables": 1.10, "default": 1.10},
        "price_floor_map": {"cables": 0.95, "default": 0.95},
        "lead_time_days": 11,
        "certifications": ["ISO-9001"],
        "trust_score": 0.73,
        "fit_score": 0.47,
    },
    {
        "id": "oz-tech-au",
        "name": "Oz Tech AU",
        "country": "AU",
        "region": "APAC",
        "capabilities": ["sensors", "motors", "batteries"],
        "base_price_map": {"sensors": 4.35, "motors": 12.20, "batteries": 8.30, "default": 6.00},
        "price_floor_map": {"sensors": 3.90, "motors": 11.10, "batteries": 7.60, "default": 5.40},
        "lead_time_days": 13,
        "certifications": ["ISO-9001", "ISO-14001"],
        "trust_score": 0.80,
        "fit_score": 0.52,
    },
    {
        "id": "nordic-precision-no",
        "name": "Nordic Precision",
        "country": "NO",
        "region": "EU",
        "capabilities": ["sensors", "connectors"],
        "base_price_map": {"sensors": 4.05, "connectors": 2.30, "default": 3.20},
        "price_floor_map": {"sensors": 3.70, "connectors": 2.00, "default": 2.80},
        "lead_time_days": 10,
        "certifications": ["CE", "ISO-9001"],
        "trust_score": 0.83,
        "fit_score": 0.55,
    },
    {
        "id": "suncoast-electronics-us",
        "name": "Suncoast Electronics",
        "country": "US",
        "region": "North America",
        "capabilities": ["displays", "batteries", "other"],
        "base_price_map": {"displays": 17.80, "batteries": 8.20, "other": 6.80, "default": 6.80},
        "price_floor_map": {"displays": 16.10, "batteries": 7.50, "other": 6.10, "default": 6.10},
        "lead_time_days": 12,
        "certifications": ["UL", "ISO-9001"],
        "trust_score": 0.79,
        "fit_score": 0.51,
    },
    {
        "id": "pacifica-assemblies-nz",
        "name": "Pacifica Assemblies",
        "country": "NZ",
        "region": "APAC",
        "capabilities": ["other", "connectors"],
        "base_price_map": {"other": 6.30, "connectors": 2.35, "default": 6.30},
        "price_floor_map": {"other": 5.70, "connectors": 2.05, "default": 5.70},
        "lead_time_days": 14,
        "certifications": ["ISO-9001"],
        "trust_score": 0.74,
        "fit_score": 0.48,
    },
    {
        "id": "sahara-components-ma",
        "name": "Sahara Components",
        "country": "MA",
        "region": "Africa",
        "capabilities": ["cables", "other"],
        "base_price_map": {"cables": 1.15, "other": 6.10, "default": 6.10},
        "price_floor_map": {"cables": 0.98, "other": 5.60, "default": 5.60},
        "lead_time_days": 16,
        "certifications": ["ISO-9001"],
        "trust_score": 0.71,
        "fit_score": 0.45,
    },
]


def seed_suppliers() -> None:
    with get_db_session() as db:
        for s in SEED_SUPPLIERS:
            existing = db.query(Supplier).filter(Supplier.id == s["id"]).first()
            if existing:
                continue
            db.add(
                Supplier(
                    id=s["id"],
                    name=s["name"],
                    country=s.get("country") or s["region"],
                    region=s["region"],
                    categories=json.dumps(s.get("categories", s["capabilities"])),
                    capabilities=json.dumps(s["capabilities"]),
                    base_price_map=json.dumps(s["base_price_map"]),
                    price_floor_map=json.dumps(s["price_floor_map"]),
                    lead_time_days=s["lead_time_days"],
                    certifications=json.dumps(s["certifications"]),
                    trust_score=s["trust_score"],
                    fit_score=s["fit_score"],
                    created_at=datetime.utcnow(),
                )
            )
        db.commit()
